import React from 'react';
import { Phone, Play, FileText, MessageCircle, X, Send, Menu, ArrowRight, Bed, Bath, DollarSign, Activity, ChevronLeft, ChevronRight, Plus, MapPin, Bookmark, Sparkles, ThumbsUp, Bell, Calendar, SlidersHorizontal, Search, ChevronDown, Maximize2, Quote, Mail, User, Check, Gem, Crown, Cloud, Wallet } from 'lucide-react';

export const PhoneIcon = () => <Phone size={16} />;
export const PlayIcon = () => <Play size={12} fill="currentColor" />;
export const DocumentIcon = () => <FileText size={24} className="transform rotate-12" />;
export const ChatIcon = () => <MessageCircle size={24} />;
export const CloseIcon = () => <X size={20} />;
export const SendIcon = () => <Send size={18} />;
export const MenuIcon = () => <Menu size={24} />;
export const ArrowRightIcon = () => <ArrowRight size={16} />;
export const BedIcon = () => <Bed size={14} />;
export const BathIcon = () => <Bath size={14} />;
export const DollarIcon = () => <DollarSign size={20} />;
export const ActivityIcon = () => <Activity size={20} />;
export const ChevronLeftIcon = () => <ChevronLeft size={20} />;
export const ChevronRightIcon = () => <ChevronRight size={20} />;
export const PlusIcon = () => <Plus size={20} />;
export const MapPinIcon = () => <MapPin size={18} />;
export const BookmarkIcon = () => <Bookmark size={18} />;
export const SparklesIcon = () => <Sparkles size={18} />;
export const ThumbsUpIcon = () => <ThumbsUp size={20} />;
export const BellIcon = () => <Bell size={18} />;
export const CalendarIcon = () => <Calendar size={18} />;
export const FilterIcon = () => <SlidersHorizontal size={16} />;
export const SearchIcon = () => <Search size={16} />;
export const ChevronDownIcon = () => <ChevronDown size={16} />;
export const AreaIcon = () => <Maximize2 size={14} />;
export const QuoteIcon = () => <Quote size={24} fill="currentColor" />;
export const MailIcon = () => <Mail size={18} />;
export const UserIcon = () => <User size={18} />;
export const CheckIcon = () => <Check size={16} />;
export const DiamondIcon = () => <Gem size={20} />;
export const CrownIcon = () => <Crown size={20} />;
export const CloudIcon = () => <Cloud size={20} />;
export const WalletIcon = () => <Wallet size={20} />;